ActiveMQ (STOMP) support
batchcorp/plumber pull request #44
Opened 2020-10-23 18:11 UTC by blinktag

2020-10-23 22:36 UTC, dselans requested changes
Two minor fixes. Looking great!

2020-10-23 22:36 UTC, dselans commented on backends/activemq/activemq.go
> +	conn, err := stomp.Dial("tcp", "localhost:61613", o)
This should be dialing the opts field.

2020-10-23 22:36 UTC, dselans commented on cli/activemq.go
> +	cmd.Flag("queue", "Topic to read message(s) from").StringVar(&opts.ActiveMq.Queue)
```suggestion
	cmd.Flag("queue", "Queue to read message(s) from").StringVar(&opts.ActiveMq.Queue)
```

2020-10-25 21:11 UTC, blinktag commented on backends/activemq/activemq.go
> +	conn, err := stomp.Dial("tcp", "localhost:61613", o)
Fixed

2020-10-27 19:01 UTC, dselans approved these changes

2020-10-27 19:01 UTC, merged